name: Pipeline Framework 4.7.2

on:
  workflow_call:
    
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: SonarQube Begin
        run: |
          SonarScanner.MSBuild.exe begin /k:"your_project_key" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://your-sonarqube-server"

      - name: Restore NuGet packages
        run: |
          nuget restore 

      - name: Build solution
        run: |
          msbuild /p:Configuration=Release /p:OutDir=${{ github.workspace }}/build-output
        
      # - name: Run tests
      #   run: |
      #     vstest.console.exe **\*Test*.dll
      #   env:
      #     VSTEST_ADDITIONAL_ARGS: '--logger:trx'

      - name: SonarQube End
        run: |
          SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"